// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Samo_GUI
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"having_IPhaving_IP_Address")]
            public float Having_IPhaving_IP_Address { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"URLURL_Length")]
            public float URLURL_Length { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Shortining_Service")]
            public float Shortining_Service { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"having_At_Symbol")]
            public float Having_At_Symbol { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"double_slash_redirecting")]
            public float Double_slash_redirecting { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Prefix_Suffix")]
            public float Prefix_Suffix { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"having_Sub_Domain")]
            public float Having_Sub_Domain { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"SSLfinal_State")]
            public float SSLfinal_State { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"port")]
            public float Port { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"HTTPS_token")]
            public float HTTPS_token { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"SFH")]
            public float SFH { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"Submitting_to_email")]
            public float Submitting_to_email { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"Abnormal_URL")]
            public float Abnormal_URL { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"Result")]
            public float Result { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"having_IPhaving_IP_Address")]
            public float Having_IPhaving_IP_Address { get; set; }

            [ColumnName(@"URLURL_Length")]
            public float URLURL_Length { get; set; }

            [ColumnName(@"Shortining_Service")]
            public float Shortining_Service { get; set; }

            [ColumnName(@"having_At_Symbol")]
            public float Having_At_Symbol { get; set; }

            [ColumnName(@"double_slash_redirecting")]
            public float Double_slash_redirecting { get; set; }

            [ColumnName(@"Prefix_Suffix")]
            public float Prefix_Suffix { get; set; }

            [ColumnName(@"having_Sub_Domain")]
            public float Having_Sub_Domain { get; set; }

            [ColumnName(@"SSLfinal_State")]
            public float SSLfinal_State { get; set; }

            [ColumnName(@"port")]
            public float Port { get; set; }

            [ColumnName(@"HTTPS_token")]
            public float HTTPS_token { get; set; }

            [ColumnName(@"SFH")]
            public float SFH { get; set; }

            [ColumnName(@"Submitting_to_email")]
            public float Submitting_to_email { get; set; }

            [ColumnName(@"Abnormal_URL")]
            public float Abnormal_URL { get; set; }

            [ColumnName(@"Result")]
            public uint Result { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("Result");
            if (labelColumn == null)
            {
                throw new Exception("Result column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<float>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
